language: python

python:
  - 2.7
  - 3.4
  - 3.5

install:
  - python setup.py install
  - pip install coveralls
  - pip install flake8

before_script:
  - flake8 cypher

script:
 - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coverage run -m unittest discover; fi
 - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then coverage run -m unittest discover; fi
 - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then coverage run -m unittest discover; fi

after_success:
  coveralls
