language: python

python:
  - 2.7
  - 3.4
  - 3.5

install:
  - python setup.py install
  - pip install coveralls

script:
 - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coverage run -m --source codetype unittest discover; fi
 - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then coverage run -m  --source codetype unittest discover; fi

after_success:
  coveralls
